on: [push]
jobs:
    build_and_static_analysis:
        runs-on: ubuntu-latest
        container:
            image: agplaza91/msp430-gcc-9.3.1.11:latest
        steps:
            - name:
                Checkout the repository
              uses:
                actions/checkout@v3
            - run:
<<<<<<< HEAD
                TOOLS_PATH=/home/ubuntu/dev_tools/ make
            - run:
                TOOLS_PATH=/home/ubuntu/dev_tools/ make cppcheck
=======
                TOOLS_PATH=/home/ubuntu/dev_tools/msp430-gcc make
            - run:
                TOOLS_PATH=/home/ubuntu/dev_tools/msp430-gcc make cppcheck
>>>>>>> 0bafd2e65de421e22c3444cb6aa731006104d744
