on: [push]
jobs:
    build_and_static_analysis:
        runs-on: ubuntu-latest
        container:
            image: agplaza91/msp430-gcc-9.3.1.11:latest
        steps:
            - name:
                Checkout the repository
              uses:
                actions/checkout@v3
            - run:
                TOOLS_PATH=/home/ubuntu/dev_tools make format && git diff --quiet
            - run:
                TOOLS_PATH=/home/ubuntu/dev_tools make cppcheck
            - run:
                TOOLS_PATH=/home/ubuntu/dev_tools make